# Generated by Django 2.2.6 on 2019-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tags', models.CharField(help_text='tags for structurazing', max_length=100)),
                ('note', models.CharField(help_text='note body', max_length=10000)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
