# Generated by Django 2.2.6 on 2019-11-03 20:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_md_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='md_field',
        ),
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=markdownx.models.MarkdownxField(help_text='note body'),
        ),
    ]
