# Generated by Django 2.2.6 on 2019-11-03 22:10

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20191103_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=entries.models.get_my_datetime),
        ),
    ]
