# Generated by Django 2.2.6 on 2019-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20191103_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, help_text='tags for structurazing', max_length=100),
        ),
    ]
