# Generated by Django 2.2.6 on 2019-11-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20191104_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, default='No tags', help_text='tags for structurazing', max_length=100),
        ),
    ]
